[package]
name = "adventofcode-2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name= 'aoc01'
path= 'src/aoc01/mod.rs'
test = true 
 